/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FORM;
import rentalmobil.ClassDatabase;
import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author USER
 */
public class FormPenyewa extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormPenyewa
     */
    public FormPenyewa() {
        initComponents();
       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        simpan = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        hapus = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnosim = new javax.swing.JTextField();
        txtnamapenyewa = new javax.swing.JTextField();
        txtnohp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtalamat = new javax.swing.JTextArea();
        txtnoktp = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_penyewa = new javax.swing.JTable();

        setInheritsPopupMenu(true);

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 51, 153));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 153, 153));

        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        jLabel3.setText("Nama");

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        jButton5.setText("Back Home");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        jLabel4.setText("No Hp");

        jLabel5.setText("No KTP");

        jLabel6.setText("Alamat");

        jLabel2.setText("No SIM");

        txtnosim.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtnosimCaretUpdate(evt);
            }
        });
        txtnosim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnosimActionPerformed(evt);
            }
        });

        txtalamat.setColumns(20);
        txtalamat.setRows(5);
        jScrollPane1.setViewportView(txtalamat);

        jButton1.setText("Tambah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORM PENYEWA MOBIL");
        jLabel1.setInheritsPopupMenu(false);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user.png"))); // NOI18N

        tbl_penyewa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ));
        jScrollPane2.setViewportView(tbl_penyewa);

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(470, 470, 470)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(97, 97, 97)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtnoktp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                        .addComponent(txtnamapenyewa, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtnohp, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtnosim, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(120, 120, 120)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(hapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(simpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtnosim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(simpan)))
                        .addGap(28, 28, 28)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtnamapenyewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edit))
                        .addGap(104, 104, 104)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnoktp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hapus))
                        .addGap(32, 32, 32)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5)))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtnohp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1))
                            .addComponent(jLabel4))
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel6)))
                .addGap(81, 81, 81)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnosimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnosimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnosimActionPerformed

    private void txtnosimCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtnosimCaretUpdate
        // TODO add your handling code here:
        try {
            Connection c=ClassDatabase.getkoneksi();
            Statement s= c.createStatement();
            String sql="Select * from penyewa where no_sim='" + this.txtnosim.getText()+"'";
            ResultSet r=s.executeQuery(sql);
            while (r.next()){
                this.txtnamapenyewa.setText(r.getString("nama_penyewa"));
                this.txtnohp.setText(r.getString("no_hp"));
                this.txtnoktp.setText(r.getString("no_ktp"));
                this.txtalamat.setText(r.getString("alamat"));

            }
            r.close();
            s.close();

        }catch(SQLException e) {
            System.out.println("Terjadi kesalahan" + e);
        }

    }//GEN-LAST:event_txtnosimCaretUpdate

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        String nosim=this.txtnosim.getText();
    String namapenyewa=this.txtnamapenyewa.getText();
    String nohp=this.txtnohp.getText();
    String noktp=this.txtnoktp.getText();
    String alamat=this.txtalamat.getText();
    
     if(txtnosim.getText().isEmpty()) 
    {
    JOptionPane.showMessageDialog(this, "Data Belum Lengkap, No Sim Tidak Boleh Kosong");
   }
    else{
    if (txtnamapenyewa.getText().isEmpty())
    {
        JOptionPane.showMessageDialog(this, "Data Belum Lengkap, Nama Penyewa Tidak Boleh Kosong");
    }
    else{
    if (txtnohp.getText().isEmpty())
    {
        JOptionPane.showMessageDialog(this, "Data Belum Lengkap, No HP Tidak Boleh Kosong");
    }
    else{
    if (txtnoktp.getText().isEmpty())
    {
        JOptionPane.showMessageDialog(this, "Data Belum Lengkap, No KTP Tidak Boleh Kosong");
    }
    else{
    if (txtalamat.getText().isEmpty())
    {
        JOptionPane.showMessageDialog(this, "Data Belum Lengkap, Alamat Tidak Boleh Kosong");
    }   
    try {
            Connection c=ClassDatabase.getkoneksi();
            String sql ="UPDATE `rentalmobil`.`penyewa` SET `nama_penyewa`=?,`no_hp` = ?,`no_ktp` =?,`alamat`= ? where `no_sim`=?";
            PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
            p.setString(5, nosim);
            p.setString(1, namapenyewa);
            p.setString(2, nohp);  
            p.setString(3, noktp);
            p.setString(4, alamat);
            p.executeUpdate();
            p.close();
            JOptionPane.showMessageDialog(this, "Sukses Update Data");
        }catch(SQLException e){
            System.out.println(e);
        }finally{
        
    }}}
    try {        
        
            Connection c=ClassDatabase.getkoneksi();
            Statement s= c.createStatement();
            String sql="select * from penyewa";
            ResultSet r=s.executeQuery(sql);
            tbl_penyewa.setModel(DbUtils.resultSetToTableModel(r));
}catch (Exception e){
JOptionPane.showMessageDialog(null, e);
}
    }}
    }//GEN-LAST:event_editActionPerformed
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
 new menuutama().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
   String idpenyewa=this.txtnosim.getText();
    
    try {
            Connection c=ClassDatabase.getkoneksi();
            String sql = "Delete from penyewa Where no_sim=?";
            PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
            p.setString(1, idpenyewa);          
           
            p.executeUpdate();
            p.close();
            JOptionPane.showMessageDialog(this, "Sukses Hapus Data");
        }catch(SQLException e){
            System.out.println(e);
        }finally{
        }
     try {        
        
            Connection c=ClassDatabase.getkoneksi();
            Statement s= c.createStatement();
            String sql="select * from penyewa";
            ResultSet r=s.executeQuery(sql);
            tbl_penyewa.setModel(DbUtils.resultSetToTableModel(r));
}catch (Exception e){
JOptionPane.showMessageDialog(null, e);
}
    }//GEN-LAST:event_hapusActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        String nosim=this.txtnosim.getText();
        String namapenyewa=this.txtnamapenyewa.getText();
        String nohp=this.txtnohp.getText();
        String noktp=this.txtnoktp.getText();
        String alamat=this.txtalamat.getText();

        if(txtnosim.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Data Belum Lengkap, Id Penyewa Tidak Boleh Kosong");
        }
        else{
            if (txtnamapenyewa.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(this, "Data Belum Lengkap, Nama Penyewa Tidak Boleh Kosong");
            }
            else{
                if (txtnohp.getText().isEmpty())
                {
                    JOptionPane.showMessageDialog(this, "Data Belum Lengkap, No Hp Tidak Boleh Kosong");
                }
                else{
                    if (txtnoktp.getText().isEmpty())
                    {
                        JOptionPane.showMessageDialog(this, "Data Belum Lengkap, Harga No ktp Tidak Boleh Kosong");
                    }
                    else{
                        if (txtalamat.getText().isEmpty())
                        {
                            JOptionPane.showMessageDialog(this, "Data Belum Lengkap, Harga Alamat Tidak Boleh Kosong");
                        }
                        else{
                            try {
                                Connection c=ClassDatabase.getkoneksi();
                                String sql = "Insert into penyewa values (?,?,?,?,?)";
                                PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
                                p.setString(1, nosim);
                                p.setString(2, namapenyewa);
                                p.setString(3, nohp);
                                p.setString(4, noktp);
                                p.setString(5, alamat);
                                p.executeUpdate();
                                p.close();

                                JOptionPane.showMessageDialog(this, "Sukses Tambah Data");

                            }catch(SQLException e){
                                System.out.println(e);
                            }finally{
                            }}}}}
                            try {

                                Connection c=ClassDatabase.getkoneksi();
                                Statement s= c.createStatement();
                                String sql="select * from penyewa";
                                ResultSet r=s.executeQuery(sql);
                                tbl_penyewa.setModel(DbUtils.resultSetToTableModel(r));
                            }catch (Exception e){
                                JOptionPane.showMessageDialog(null, e);
                            }
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     txtnosim.setText("");
           txtnamapenyewa.setText("");
           txtnohp.setText("");
           txtnoktp.setText("");
           txtalamat.setText("");
     txtnosim.requestFocus();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton edit;
    private javax.swing.JButton hapus;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tbl_penyewa;
    private javax.swing.JTextArea txtalamat;
    private javax.swing.JTextField txtnamapenyewa;
    private javax.swing.JTextField txtnohp;
    private javax.swing.JTextField txtnoktp;
    private javax.swing.JTextField txtnosim;
    // End of variables declaration//GEN-END:variables

    private void setLocationRelativeTo(FormPenyewa This) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
